(()=>{
  'use strict';
  const KEY='lfinance-data-v1', defaults={userName:'Lucas',currency:'BRL',categories:['Moradia','Alimentação','Transporte','Saúde','Lazer','Salário','Compras','Contas','Outros'],transactions:[],cards:[]};
  const clone=x=>JSON.parse(JSON.stringify(x));let state=load(),view='inicio',filter='Todos',toastTimer;
  function load(){try{return {...clone(defaults),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return clone(defaults)}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:state.currency||'BRL'}).format(Number(n)||0);
  const dateNow=()=>new Date().toISOString().slice(0,10);const inMonth=d=>String(d||'').slice(0,7)===dateNow().slice(0,7);
  const totals=()=>{const month=state.transactions.filter(t=>inMonth(t.date));return {income:month.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0),expense:month.filter(t=>t.type!=='income').reduce((s,t)=>s+t.amount,0),balance:state.transactions.reduce((s,t)=>s+(t.type==='income'?t.amount:-t.amount),0)}};
  function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
  const icons={Moradia:'⌂',Alimentação:'♨',Transporte:'↗',Saúde:'✚',Lazer:'✦',Salário:'↙',Compras:'◇',Contas:'▤',Outros:'◉'};
  function render(){const root=$('#view');if(view==='inicio')root.innerHTML=home();if(view==='lancamentos')root.innerHTML=transactionsPage();if(view==='cartoes')root.innerHTML=cardsPage();if(view==='ajustes')root.innerHTML=settingsPage();$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));bindPage()}
  function home(){const t=totals(),byCategory={};state.transactions.filter(x=>x.type!=='income'&&inMonth(x.date)).forEach(x=>byCategory[x.category]=(byCategory[x.category]||0)+x.amount);const cats=Object.entries(byCategory).sort((a,b)=>b[1]-a[1]).slice(0,5),maxCat=Math.max(1,...cats.map(x=>x[1]));const months=Array.from({length:6},(_,i)=>{let d=new Date();d.setDate(1);d.setMonth(d.getMonth()-5+i);return {key:d.toISOString().slice(0,7),label:d.toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}});const values=months.map(m=>state.transactions.filter(x=>x.type!=='income'&&String(x.date).slice(0,7)===m.key).reduce((s,x)=>s+x.amount,0)),max=Math.max(1,...values);const invoice=invoiceTotal();const recent=[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);
    return `<section class="page"><div class="welcome"><div><p class="eyebrow">SEU RESUMO FINANCEIRO</p><h1>Olá, ${esc(state.userName)} 👋</h1><p class="muted">Veja como está sua vida financeira.</p></div><div class="month-pill">${new Date().toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</div></div>
      <div class="overview"><article class="balance-card"><div class="balance-label">Saldo disponível</div><div class="balance">${money(t.balance)}</div><div class="balance-foot"><span>↗</span> Seu saldo considerando todos os lançamentos</div></article>
      <article class="metric-card"><div class="metric-top"><span>Receitas no mês</span><span class="metric-icon">↙</span></div><div class="metric-value positive">${money(t.income)}</div><div class="legend">Entradas registradas</div></article>
      <article class="metric-card"><div class="metric-top"><span>Despesas no mês</span><span class="metric-icon" style="color:var(--red);background:#302126">↗</span></div><div class="metric-value">${money(t.expense)}</div><div class="legend">Saídas registradas</div></article></div>
      <div class="content-grid"><section class="panel"><div class="panel-head"><h2>Gastos do mês</h2><span class="legend">Últimos 6 meses</span></div><div class="chart">${months.map((m,i)=>`<div class="chart-col"><div class="bar-track"><div class="bar" style="height:${Math.max(values[i]?5:0,Math.round(values[i]/max*100))}%"></div></div><span>${m.label}</span></div>`).join('')}</div></section>
      <section class="panel"><div class="panel-head"><h2>Gastos por categoria</h2><button class="text-button" data-goto="lancamentos">Ver tudo</button></div>${cats.length?`<div class="category-list">${cats.map(([name,value])=>`<div class="category-row"><span class="category-icon">${icons[name]||'◉'}</span><div><div class="category-name">${esc(name)}</div><div class="category-track"><div class="category-progress" style="width:${value/maxCat*100}%"></div></div></div><span class="category-amount">${money(value)}</span></div>`).join('')}</div>`:'<div class="empty">Seus gastos por categoria aparecerão aqui.</div>'}</section></div>
      <section class="panel" style="margin-top:15px"><div class="panel-head"><h2>Cartão de crédito</h2><button class="text-button" data-goto="cartoes">Meus cartões →</button></div>${state.cards.length?`<div class="card-summary"><div class="summary-box"><span>Fatura atual</span><strong>${money(invoice)}</strong></div><div class="summary-box"><span>Cartões cadastrados</span><strong>${state.cards.length}</strong></div></div>`:`<div class="empty">Cadastre um cartão para acompanhar sua fatura e parcelas.</div>`}</section>
      <section class="panel recent-panel"><div class="panel-head"><h2>Lançamentos recentes</h2><button class="text-button" data-goto="lancamentos">Ver todos →</button></div>${transactionRows(recent)}</section></section>`}
  function transactionRows(items){if(!items.length)return '<div class="empty">Nenhum lançamento por aqui ainda. Toque no + para começar.</div>';return `<div class="transaction-list">${items.map(t=>`<article class="transaction"><span class="transaction-icon">${t.type==='income'?'↙':t.type==='card'?'▤':icons[t.category]||'◉'}</span><div><div class="transaction-name">${esc(t.description)}</div><div class="transaction-meta">${esc(t.category)} · ${new Date(t.date+'T12:00:00').toLocaleDateString('pt-BR')}${t.installments>1?` · ${t.installments}x`:''}</div></div><div class="transaction-value ${t.type==='income'?'positive':''}">${t.type==='income'?'+':'−'} ${money(t.amount)}</div><div class="transaction-actions"><button class="small-action" data-edit="${t.id}" aria-label="Editar">✎</button><button class="small-action" data-delete="${t.id}" aria-label="Excluir">×</button></div></article>`).join('')}</div>`}
  function transactionsPage(){const items=[...state.transactions].filter(t=>filter==='Todos'||(filter==='Receitas'?t.type==='income':t.type!=='income')).sort((a,b)=>b.date.localeCompare(a.date));return `<section class="page"><p class="eyebrow">MOVIMENTAÇÕES</p><h1 class="page-title">Lançamentos</h1><p class="page-subtitle">Acompanhe todas as entradas e saídas.</p><div class="toolbar"><div class="list-filters">${['Todos','Receitas','Despesas'].map(f=>`<button class="filter-chip ${filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div><button class="button" id="voiceOpen">🎙️ Voz</button></div><section class="panel">${transactionRows(items)}</section></section>`}
  function invoiceTotal(cardId){const now=new Date(),month=now.getFullYear()*12+now.getMonth();return state.transactions.filter(t=>t.type==='card'&&(!cardId||t.cardId===cardId)).reduce((sum,t)=>{const start=new Date(t.date+'T12:00:00'),offset=month-(start.getFullYear()*12+start.getMonth()),parts=Math.max(1,Number(t.installments)||1);return sum+(offset>=0&&offset<parts?t.amount/parts:0)},0)}
  function futureInstallments(cardId){const out=[];state.transactions.filter(t=>t.type==='card'&&t.cardId===cardId&&t.installments>1).forEach(t=>{for(let i=1;i<t.installments;i++){const d=new Date(t.date+'T12:00:00');d.setMonth(d.getMonth()+i);out.push({date:d,amount:t.amount/t.installments,description:t.description})}});return out.sort((a,b)=>a.date-b.date)}
  function cardsPage(){return `<section class="page"><p class="eyebrow">CRÉDITO</p><h1 class="page-title">Cartões</h1><p class="page-subtitle">Faturas e parcelas em um só lugar.</p><div class="toolbar"><span class="muted">${state.cards.length} cartão(ões)</span><button class="button primary" id="addCard">＋ Novo cartão</button></div>${state.cards.length?`<div class="card-grid">${state.cards.map(c=>{const inv=invoiceTotal(c.id),used=Math.min(100,c.limit?inv/c.limit*100:0),future=futureInstallments(c.id);return `<article class="credit-card"><div class="credit-name">${esc(c.name)}</div><div class="card-number">•••• &nbsp;•••• &nbsp;•••• &nbsp;${String(c.name).replace(/\W/g,'').slice(-4).toUpperCase().padStart(4,'0')}</div><div class="card-limit"><span>Utilizado ${money(inv)}</span><span>Limite ${money(c.limit)}</span></div><div class="progress-track"><div class="progress-fill" style="width:${used}%"></div></div><div class="card-summary"><div class="summary-box"><span>Fatura atual</span><strong>${money(inv)}</strong></div><div class="summary-box"><span>Disponível</span><strong>${money(Math.max(0,c.limit-inv))}</strong></div></div>${future.length?`<div class="installment-list"><strong>Parcelas futuras</strong><br>${future.slice(0,5).map(p=>`${p.date.toLocaleDateString('pt-BR',{month:'short',year:'numeric'})} · ${esc(p.description)} · ${money(p.amount)}`).join('<br>')}${future.length>5?`<br>+ ${future.length-5} parcelas`:''}</div>`:'<div class="installment-list">Sem parcelas futuras.</div>'}<button class="text-button" data-delete-card="${c.id}">Remover cartão</button></article>`}).join('')}</div>`:'<section class="panel empty">Você ainda não cadastrou cartões.<br><button class="button primary" id="addCard" style="margin-top:14px">＋ Adicionar cartão</button></section>'}</section>`}
  function settingsPage(){return `<section class="page"><p class="eyebrow">PREFERÊNCIAS</p><h1 class="page-title">Ajustes</h1><p class="page-subtitle">Personalize seu espaço e seus dados.</p><div class="settings-grid"><section class="setting-card"><h2>Seu perfil</h2><label>Nome<input id="userName" value="${esc(state.userName)}" maxlength="40"></label><label>Moeda<select id="currency"><option value="BRL" ${state.currency==='BRL'?'selected':''}>Real brasileiro (BRL)</option><option value="USD" ${state.currency==='USD'?'selected':''}>Dólar americano (USD)</option><option value="EUR" ${state.currency==='EUR'?'selected':''}>Euro (EUR)</option></select></label><button class="button primary" id="saveProfile">Salvar perfil</button></section><section class="setting-card"><h2>Categorias</h2><div class="category-editor">${state.categories.map(c=>`<span class="category-tag">${esc(c)}<button data-remove-category="${esc(c)}" aria-label="Remover ${esc(c)}">×</button></span>`).join('')}</div><div class="form-row"><input id="newCategory" placeholder="Nova categoria"><button class="button" id="addCategory">Adicionar</button></div><p>Use categorias para organizar seus lançamentos.</p></section><section class="setting-card"><h2>Seus dados</h2><p>Seus registros ficam salvos somente neste dispositivo.</p><div class="settings-actions"><button class="button" id="exportData">⇩ Exportar dados (JSON)</button><button class="button" id="importData">⇧ Importar dados (JSON)</button><input class="hidden" id="importFile" type="file" accept="application/json,.json"><button class="button danger" id="clearTransactions">Apagar lançamentos</button><button class="button danger" id="resetData">Zerar todos os dados</button></div></section><section class="setting-card"><h2>Privacidade e offline</h2><p>O LFINANCE não envia seus dados para servidores. O app pode ser instalado na tela inicial e continua disponível sem conexão após a primeira visita.</p><p>Para instalar no iPhone: abra no Safari, toque em Compartilhar e escolha “Adicionar à Tela de Início”.</p></section></div></section>`}
  function bindPage(){ $$('[data-goto]').forEach(b=>b.onclick=()=>navigate(b.dataset.goto));$$('[data-edit]').forEach(b=>b.onclick=()=>openEntry(b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>{state.transactions=state.transactions.filter(t=>t.id!==b.dataset.delete);save();toast('Lançamento excluído')});$$('[data-delete-card]').forEach(b=>b.onclick=()=>{if(state.transactions.some(t=>t.type==='card'&&t.cardId===b.dataset.delete)){toast('Este cartão tem compras vinculadas');return}state.cards=state.cards.filter(c=>c.id!==b.dataset.delete);save();toast('Cartão removido')});$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});$('#voiceOpen')?.addEventListener('click',()=>$('#voiceDialog').showModal());$('#addCard')?.addEventListener('click',()=>$('#cardDialog').showModal());$('#saveProfile')?.addEventListener('click',()=>{state.userName=$('#userName').value.trim()||'Lucas';state.currency=$('#currency').value;save();toast('Perfil atualizado')});$('#addCategory')?.addEventListener('click',()=>{const el=$('#newCategory'),v=el.value.trim();if(v&&!state.categories.includes(v)){state.categories.push(v);save();toast('Categoria adicionada')}});$$('[data-remove-category]').forEach(b=>b.onclick=()=>{if(state.categories.length<=1){toast('Mantenha ao menos uma categoria');return}state.categories=state.categories.filter(c=>c!==b.dataset.removeCategory);save()});$('#exportData')?.addEventListener('click',exportData);$('#importData')?.addEventListener('click',()=>$('#importFile').click());$('#importFile')?.addEventListener('change',importData);$('#clearTransactions')?.addEventListener('click',()=>{if(confirm('Apagar todos os lançamentos?')){state.transactions=[];save();toast('Lançamentos apagados')}});$('#resetData')?.addEventListener('click',()=>{if(confirm('Zerar todos os dados e voltar às configurações iniciais?')){state=clone(defaults);save();toast('Dados zerados')}})}
  function navigate(to){view=to;render();window.scrollTo({top:0,behavior:'smooth'})}
  function openEntry(id){const form=$('#entryForm'),entry=state.transactions.find(t=>t.id===id);form.reset();form.elements.namedItem('id').value=entry?.id||'';$('#entryTitle').textContent=entry?'Editar lançamento':'Novo lançamento';const types=$$('.type-switch button');types.forEach(b=>b.classList.toggle('selected',b.dataset.type===(entry?.type||'expense')));form.elements.namedItem('description').value=entry?.description||'';form.elements.namedItem('amount').value=entry?.amount||'';form.elements.namedItem('date').value=entry?.date||dateNow();form.elements.namedItem('payment').value=entry?.payment||'Pix';form.elements.namedItem('installments').value=entry?.installments||1;fillSelect(form.elements.namedItem('category'),state.categories,entry?.category);fillSelect(form.elements.namedItem('cardId'),state.cards.map(c=>({id:c.id,name:c.name})),entry?.cardId);$('.card-fields').classList.toggle('hidden',(entry?.type||'expense')!=='card');$('#entryDialog').showModal()}
  function fillSelect(select,items,selected){select.replaceChildren();items.forEach(item=>{const value=typeof item==='string'?item:item.id,label=typeof item==='string'?item:item.name,o=document.createElement('option');o.value=value;o.textContent=label;o.selected=value===selected;select.append(o)})}
  $$('.type-switch button').forEach(b=>b.onclick=()=>{$$('.type-switch button').forEach(x=>x.classList.toggle('selected',x===b));$('.card-fields').classList.toggle('hidden',b.dataset.type!=='card')});
  $('#entryForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,type=$('.type-switch button.selected').dataset.type,amount=Number(f.elements.namedItem('amount').value),id=f.elements.namedItem('id').value||crypto.randomUUID();if(!amount||amount<=0){toast('Informe um valor válido');return}if(type==='card'&&!f.elements.namedItem('cardId').value){toast('Cadastre um cartão primeiro');return}const item={id,type,description:f.elements.namedItem('description').value.trim(),amount,category:f.elements.namedItem('category').value||'Outros',date:f.elements.namedItem('date').value,payment:type==='card'?'Crédito':f.elements.namedItem('payment').value,cardId:type==='card'?f.elements.namedItem('cardId').value:null,installments:type==='card'?Math.max(1,Number(f.elements.namedItem('installments').value)||1):1};const i=state.transactions.findIndex(t=>t.id===id);if(i<0)state.transactions.push(item);else state.transactions[i]=item;$('#entryDialog').close();save();toast(i<0?'Lançamento salvo':'Lançamento atualizado')});
  $('#cardForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;state.cards.push({id:crypto.randomUUID(),name:f.name.value.trim(),limit:Number(f.limit.value),closingDay:Number(f.closingDay.value)||25});$('#cardDialog').close();save();toast('Cartão cadastrado')});
  $('#quickAdd').onclick=()=>{if(view!=='inicio')navigate('inicio');if(!state.categories.length)state.categories=clone(defaults.categories);openEntry()};$('#profileShortcut').onclick=()=>navigate('ajustes');
  function exportData(){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=url;a.download=`lfinance-backup-${dateNow()}.json`;a.click();URL.revokeObjectURL(url);toast('Backup exportado')}
  function importData(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.transactions)||!Array.isArray(data.cards)||!Array.isArray(data.categories))throw Error();state={...clone(defaults),...data};save();toast('Dados importados')}catch{toast('Arquivo inválido do LFINANCE')}e.target.value=''};reader.readAsText(file)}
  function parseVoice(text){const lower=text.toLocaleLowerCase('pt-BR');let type=/\b(recebi|receita|ganhei|sal[aá]rio|rendimento|entrada)\b/.test(lower)?'income':/\b(cart[aã]o|cr[eé]dito|parcelad[oa]|comprei)\b/.test(lower)?'card':'expense';let match=lower.match(/(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)(?:\s*reais?)?/);if(!match){toast('Não encontrei um valor. Tente falar, por exemplo, “gastei 85 reais no mercado”.');return}let amount=Number(match[1].replace(',','.'));const description=text.replace(match[0],'').replace(/\b(gastei|gastar|paguei|pagar|comprei|recebi|ganhei|reais?|de|no|na|em|para|por|um|uma)\b/gi,' ').replace(/\s+/g,' ').trim()||'Lançamento por voz';let category=state.categories.find(c=>lower.includes(c.toLocaleLowerCase('pt-BR')));if(!category){if(/mercado|supermercado|restaurante|lanche|comida|padaria/.test(lower))category=state.categories.find(c=>/aliment/i.test(c));else if(/sal[aá]rio|recebi/.test(lower))category=state.categories.find(c=>/sal[aá]rio|receita/i.test(c));else if(/uber|combust[ií]vel|gasolina|ônibus|onibus/.test(lower))category=state.categories.find(c=>/transporte/i.test(c))}$('#voiceDialog').close();openEntry();const f=$('#entryForm');f.description.value=description[0].toUpperCase()+description.slice(1);f.amount.value=amount;f.category.value=category||state.categories.at(-1)||'Outros';$$('.type-switch button').forEach(b=>b.classList.toggle('selected',b.dataset.type===type));$('.card-fields').classList.toggle('hidden',type!=='card');if(type==='card'&&!state.cards.length){toast('Cadastre um cartão e selecione-o para concluir');$('.card-fields').classList.remove('hidden')} }
  $('#parseVoice').onclick=()=>parseVoice($('#voiceText').value.trim());
  $('#startVoice').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Reconhecimento de voz indisponível neste navegador. Digite sua frase abaixo.');return}const recognition=new SR();recognition.lang='pt-BR';recognition.interimResults=false;$('#voiceResult').textContent='Estou ouvindo…';recognition.onresult=e=>{const text=e.results[0][0].transcript;$('#voiceText').value=text;$('#voiceResult').textContent=`Entendi: “${text}”`;parseVoice(text)};recognition.onerror=()=>$('#voiceResult').textContent='Não consegui ouvir. Confira a permissão do microfone e tente novamente.';recognition.start()};
  document.addEventListener('click',e=>{const b=e.target.closest('[data-goto]');if(b)navigate(b.dataset.goto)});
  render();if('serviceWorker'in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
